### ISSUE TITLE
nativeMain build error (commonMain -> mingwX64 native

### ISSUE THREAD

**Issue by hansimmmi** [ionspin/kotlin-multiplatform-libsodium#29] opened 2022-10-05 08:21 UTC
Hi, I am trying to test the module on Multiplatform on android, iOS and native platform, Kmm project build fine for android and IOS project, but error with native Main. 

simply added sourceSet of commonMain with 

`implementation("com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7") `

My mingwX64 setup is

`mingwX64("native")
    {
        binaries {
            sharedLib {
                baseName = "libnative"
            }
        }
    }`

Any idea?

`mtkSharedModule:nativeMain: Could not resolve com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7.
Required by:
    project :

Possible solution:
 - Declare repository providing the artifact, see the documentation at https://docs.gradle.org/current/userguide/declaring_repositories.html`

**Comment by hansimmmi** [comment] 2022-10-05 08:23
more error message,

`Execution failed for task ':compileKotlinNative'.
Could not resolve all files for configuration ':nativeCompileKlibraries'.
   > Could not resolve com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7.
     Required by:
         project :
      > No matching variant of com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 was found. The consumer was configured to find a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native', attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64' but:
          - Variant 'debugApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares an API of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'debugRuntimeElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a runtime of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'androidJvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'iosArm32ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm32' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosArm32MetadataElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm32' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosArm64ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosArm64MetadataElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_arm64' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosSimulatorArm64ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosSimulatorArm64MetadataElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_simulator_arm64' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosX64ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'iosX64MetadataElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a usage of 'kotlin-metadata' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'ios_x64' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'jsApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'jsRuntimeElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a library:
              - Incompatible because this component declares a usage of 'kotlin-runtime' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'js' and the consumer needed a usage of 'kotlin-api' of a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'jvmApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares an API of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'jvmRuntimeElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a runtime of a library:
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'jvm' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native'
              - Other compatible attribute:
                  - Doesn't say anything about org.jetbrains.kotlin.native.target (required 'mingw_x64')
          - Variant 'linuxArm64ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'linux_arm64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'
          - Variant 'linuxX64ApiElements-published' capability com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.7 declares a usage of 'kotlin-api' of a library, as well as attribute 'org.jetbrains.kotlin.platform.type' with value 'native':
              - Incompatible because this component declares a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'linux_x64' and the consumer needed a component, as well as attribute 'org.jetbrains.kotlin.native.target' with value 'mingw_x64'`

**Comment by ionspin** [comment] 2022-10-05 08:25
Thanks for the logs! I'll have a look into it.

**Comment by ionspin** [comment] 2022-10-05 08:33
The artifact for mingwx64 is published, but the common library module.xml doesn't contain it. I'll have to look into what is going on with gradle publishing there.

**Comment by ionspin** [comment] 2022-10-05 10:13
Hey @hansimmmi this should be fixed in the snapshot release now. 

The original cause was somewhat of a regression. When kotlin enabled automatic cross-compiling on linux for windows targets I disabled windows target on linux build because it didn't have access to libsodium that was being built on a real windows machine. I forgot that it will remove mingw from the module.xml. Now it's fixed by leaving the target on linux, but disabling linking, compilation and publishing.

Could you please try the snapshot and tell me if everything is working as expected?

This is the snapshot version setup:
```
repositories {
    maven("https://oss.sonatype.org/content/repositories/snapshots")
}
implementation("com.ionspin.kotlin:multiplatform-crypto-libsodium-bindings:0.8.8-SNAPSHOT")
```

If everything is fine I'll release a stable 0.8.8 with this fix.

Thanks!

**Comment by hansimmmi** [comment] 2022-10-06 01:45
Just in case, I ran build the module in Windows machine, has similar issue with snapshot build.

`Could not find "C:\Users\*\.gradle\caches\modules-2\files-2.1\com.ionspin.kotlin\multiplatform-crypto-libsodium-bindings-mingwx64\0.8.8-SNAPSHOT\b9379b704812f6ae81738b6abc20ef3ec1c06371\multiplatform-crypto-libsodium-bindings-mingwx64-0.8.8-SNAPSHOT.klib" in [D:\*\work\*, C:\Users\*\.konan\klib, C:\Users\*\.konan\kotlin-native-prebuilt-windows-x86_64-1.6.0\klib\common, C:\Users\*\.konan\kotlin-native-prebuilt-windows-x86_64-1.6.0\klib\platform\mingw_x64]`

**Comment by ionspin** [comment] 2022-10-06 09:51
Hi @hansimmmi , I tried the latests snapshot by using a standalone project on mac, windows and a fresh linux virtual machine and I cannot reproduce the problem you are seeing and I suspect it might be a problem with your gradle caches. Could you try to run your gradle build with `--refresh-dependencies` and if that doesn't work clear the gradle cache?

**Comment by hansimmmi** [comment] 2022-10-07 10:03
@ionspin After remove all the caches it build ok now. Thank you for prompt action!
I think you can update 0.8.8 now!

**Closed** 2022-10-09 09:57 UTC
